import { useState } from "react";
import { Patient, Disease } from "@/types/scan";
import { Download, Stethoscope, User, Camera, AlertTriangle, CheckCircle, Clock, Lightbulb, Lock, Unlock } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface PatientReportProps {
  patient: Patient | null;
  reportType: 'doctor' | 'patient';
  isEditMode: boolean;
  onRequestEdit: () => void;
}

export function PatientReport({ patient, reportType, isEditMode, onRequestEdit }: PatientReportProps) {
  const [editedNotes, setEditedNotes] = useState<Record<string, string>>({});

  if (!patient) {
    return (
      <div style={{ 
        height: '100%', 
        display: 'flex', 
        alignItems: 'center', 
        justifyContent: 'center',
        flexDirection: 'column',
        color: '#6b7280',
      }}>
        <Stethoscope size={48} style={{ marginBottom: '16px', color: '#9ca3af' }} />
        <p style={{ fontSize: '18px' }}>Select a patient to view their report</p>
      </div>
    );
  }

  const calculateOverallRisk = (): { level: string; color: string } => {
    const allDiseases = patient.scans.flatMap(s => s.diseases);
    const maxProb = Math.max(...allDiseases.map(d => d.probability), 0);
    if (maxProb >= 70) return { level: 'High Risk', color: '#ef4444' };
    if (maxProb >= 40) return { level: 'Moderate Risk', color: '#f59e0b' };
    return { level: 'Low Risk', color: '#22c55e' };
  };

  const generateComprehensiveReport = (): Disease[] => {
    const allDiseases = patient.scans.flatMap(s => s.diseases);
    const uniqueDiseases = allDiseases.reduce((acc, d) => {
      const existing = acc.find(e => e.name === d.name);
      if (!existing || existing.probability < d.probability) {
        return [...acc.filter(e => e.name !== d.name), d];
      }
      return acc;
    }, [] as Disease[]);
    return uniqueDiseases.sort((a, b) => b.probability - a.probability);
  };

  const risk = calculateOverallRisk();
  const diseases = generateComprehensiveReport();

  const downloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(8, 145, 178);
    doc.text("EyeQ by LucidEye", 20, 20);
    
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(reportType === 'doctor' ? "Medical Report (Clinical)" : "Patient Health Summary", 20, 35);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 42);

    // Patient Info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Patient: ${patient.name}`, 20, 55);
    doc.text(`Age: ${patient.age || 'N/A'} | Gender: ${patient.gender ? patient.gender.charAt(0).toUpperCase() + patient.gender.slice(1) : 'N/A'}`, 20, 62);
    doc.text(`DOB: ${new Date(patient.dateOfBirth).toLocaleDateString()}`, 20, 69);
    doc.text(`Total Scans: ${patient.scans.length}`, 20, 76);
    doc.text(`Risk Level: ${risk.level}`, 20, 83);
    if (patient.relevantInfo) {
      doc.text(`Medical History: ${patient.relevantInfo.substring(0, 60)}${patient.relevantInfo.length > 60 ? '...' : ''}`, 20, 90);
    }

    // Diseases Table
    const tableStartY = patient.relevantInfo ? 105 : 95;
    if (diseases.length > 0) {
      doc.setFontSize(14);
      doc.text(reportType === 'doctor' ? "Clinical Findings" : "Health Findings", 20, tableStartY - 5);

      const tableData = diseases.map(d => [
        d.name,
        `${d.probability}%`,
        d.severity.toUpperCase(),
        reportType === 'doctor' 
          ? d.description 
          : d.probability >= 70 ? 'Needs attention' : d.probability >= 40 ? 'Monitor' : 'Looking good'
      ]);

      autoTable(doc, {
        startY: tableStartY,
        head: [['Condition', 'Probability', 'Severity', reportType === 'doctor' ? 'Clinical Notes' : 'Status']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [8, 145, 178] },
        styles: { fontSize: 9 },
        columnStyles: {
          0: { cellWidth: 40 },
          1: { cellWidth: 25 },
          2: { cellWidth: 25 },
          3: { cellWidth: 'auto' },
        },
      });
    }

    // Recommendations
    const finalY = (doc as any).lastAutoTable?.finalY || 120;
    doc.setFontSize(12);
    doc.text("Recommendations", 20, finalY + 15);
    doc.setFontSize(10);
    const recommendation = risk.level === 'High Risk' 
      ? 'Immediate specialist consultation recommended.'
      : risk.level === 'Moderate Risk'
      ? 'Follow-up appointment within 3-6 months recommended.'
      : 'Continue routine monitoring as per standard guidelines.';
    doc.text(recommendation, 20, finalY + 25);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("This report is generated by AI analysis and should be verified by a medical professional.", 20, 280);

    doc.save(`${patient.name.replace(/\s+/g, '_')}_${reportType}_report.pdf`);
  };

  if (reportType === 'doctor') {
    return (
      <div style={{ padding: '24px', overflowY: 'auto', height: '100%' }}>
        {/* Header */}
        <div style={{ 
          backgroundColor: 'white', 
          borderRadius: '12px', 
          padding: '24px',
          marginBottom: '24px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                <Stethoscope size={28} style={{ color: '#0891b2' }} />
                <h2 style={{ fontSize: '24px', fontWeight: 700, color: '#111' }}>Clinical Report</h2>
              </div>
              <p style={{ color: '#6b7280' }}>
                Patient: {patient.name} | Age: {patient.age || 'N/A'} | Gender: {patient.gender ? patient.gender.charAt(0).toUpperCase() + patient.gender.slice(1) : 'N/A'}
              </p>
            </div>
            <div style={{ display: 'flex', gap: '12px' }}>
              <button
                onClick={onRequestEdit}
                style={{
                  padding: '10px 16px',
                  borderRadius: '8px',
                  border: '1px solid #e5e7eb',
                  backgroundColor: 'white',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                  fontWeight: 500,
                  color: isEditMode ? '#22c55e' : '#6b7280',
                }}
              >
                {isEditMode ? <Unlock size={16} /> : <Lock size={16} />}
                {isEditMode ? 'Edit Mode' : 'View Only'}
              </button>
              <button
                onClick={downloadPDF}
                style={{
                  padding: '10px 16px',
                  borderRadius: '8px',
                  border: 'none',
                  backgroundColor: '#0891b2',
                  color: 'white',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                  fontWeight: 500,
                }}
              >
                <Download size={16} /> Download PDF
              </button>
            </div>
          </div>
          <div style={{
            marginTop: '16px',
            padding: '12px 16px',
            borderRadius: '8px',
            backgroundColor: risk.color + '15',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
          }}>
            <AlertTriangle size={20} style={{ color: risk.color }} />
            <span style={{ fontWeight: 600, color: risk.color }}>{risk.level}</span>
            <span style={{ color: '#6b7280', marginLeft: '8px' }}>
              Based on {patient.scans.length} scan(s) analyzed
            </span>
          </div>
        </div>

        {/* Scans Overview */}
        <div style={{ 
          backgroundColor: 'white', 
          borderRadius: '12px', 
          padding: '24px',
          marginBottom: '24px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
        }}>
          <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Camera size={20} /> Imaging Studies ({patient.scans.length})
          </h3>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: '12px' }}>
            {patient.scans.map((scan) => (
              <div key={scan.id} style={{ 
                border: '1px solid #e5e7eb', 
                borderRadius: '8px', 
                overflow: 'hidden',
              }}>
                <img src={scan.imageUrl} alt={scan.name} style={{ width: '100%', height: '120px', objectFit: 'cover' }} />
                <div style={{ padding: '10px' }}>
                  <p style={{ fontWeight: 500, fontSize: '13px' }}>{scan.name}</p>
                  <p style={{ fontSize: '11px', color: '#6b7280' }}>{scan.type.toUpperCase()} • {scan.uploadedAt.toLocaleDateString()}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Clinical Findings */}
        <div style={{ 
          backgroundColor: 'white', 
          borderRadius: '12px', 
          padding: '24px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
        }}>
          <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '16px' }}>Clinical Findings</h3>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ backgroundColor: '#f3f4f6' }}>
                <th style={{ padding: '12px', textAlign: 'left', fontSize: '13px' }}>Condition</th>
                <th style={{ padding: '12px', textAlign: 'left', fontSize: '13px' }}>Probability</th>
                <th style={{ padding: '12px', textAlign: 'left', fontSize: '13px' }}>Severity</th>
                <th style={{ padding: '12px', textAlign: 'left', fontSize: '13px' }}>Notes</th>
              </tr>
            </thead>
            <tbody>
              {diseases.map((disease, idx) => (
                <tr key={idx} style={{ borderBottom: '1px solid #e5e7eb' }}>
                  <td style={{ padding: '12px', fontWeight: 500, fontSize: '14px' }}>{disease.name}</td>
                  <td style={{ padding: '12px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <div style={{ width: '50px', height: '6px', backgroundColor: '#e5e7eb', borderRadius: '3px', overflow: 'hidden' }}>
                        <div style={{ width: `${disease.probability}%`, height: '100%', backgroundColor: disease.probability >= 70 ? '#ef4444' : disease.probability >= 40 ? '#f59e0b' : '#22c55e' }} />
                      </div>
                      <span style={{ fontSize: '13px', fontWeight: 600 }}>{disease.probability}%</span>
                    </div>
                  </td>
                  <td style={{ padding: '12px' }}>
                    <span style={{
                      padding: '3px 8px',
                      borderRadius: '10px',
                      fontSize: '11px',
                      fontWeight: 600,
                      backgroundColor: disease.severity === 'high' ? '#fef2f2' : disease.severity === 'medium' ? '#fffbeb' : '#f0fdf4',
                      color: disease.severity === 'high' ? '#ef4444' : disease.severity === 'medium' ? '#f59e0b' : '#22c55e',
                    }}>
                      {disease.severity.toUpperCase()}
                    </span>
                  </td>
                  <td style={{ padding: '12px' }}>
                    {isEditMode ? (
                      <textarea
                        value={editedNotes[disease.name] ?? disease.description}
                        onChange={(e) => setEditedNotes({ ...editedNotes, [disease.name]: e.target.value })}
                        style={{
                          width: '100%',
                          padding: '8px',
                          borderRadius: '6px',
                          border: '1px solid #e5e7eb',
                          fontSize: '13px',
                          minHeight: '60px',
                          resize: 'vertical',
                        }}
                      />
                    ) : (
                      <span style={{ fontSize: '13px', color: '#6b7280' }}>
                        {editedNotes[disease.name] ?? disease.description}
                      </span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    );
  }

  // Patient-friendly report
  return (
    <div style={{ padding: '24px', overflowY: 'auto', height: '100%' }}>
      {/* Header */}
      <div style={{ 
        backgroundColor: 'white', 
        borderRadius: '12px', 
        padding: '24px',
        marginBottom: '24px',
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
              <User size={28} style={{ color: '#0891b2' }} />
              <h2 style={{ fontSize: '24px', fontWeight: 700, color: '#111' }}>Your Eye Health Summary</h2>
            </div>
            <p style={{ color: '#6b7280' }}>Hello, {patient.name.split(' ')[0]}! Here's an easy-to-understand overview of your eye health.</p>
          </div>
          <button
            onClick={downloadPDF}
            style={{
              padding: '10px 16px',
              borderRadius: '8px',
              border: 'none',
              backgroundColor: '#0891b2',
              color: 'white',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              fontWeight: 500,
            }}
          >
            <Download size={16} /> Download PDF
          </button>
        </div>
      </div>

      {/* Overall Status */}
      <div style={{ 
        backgroundColor: risk.level === 'Low Risk' ? '#f0fdf4' : risk.level === 'Moderate Risk' ? '#fffbeb' : '#fef2f2',
        borderRadius: '12px', 
        padding: '24px',
        marginBottom: '24px',
        border: `2px solid ${risk.color}20`,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          {risk.level === 'Low Risk' ? (
            <CheckCircle size={48} style={{ color: '#22c55e' }} />
          ) : risk.level === 'Moderate Risk' ? (
            <Clock size={48} style={{ color: '#f59e0b' }} />
          ) : (
            <AlertTriangle size={48} style={{ color: '#ef4444' }} />
          )}
          <div>
            <h3 style={{ fontSize: '22px', fontWeight: 700, color: risk.color }}>{risk.level}</h3>
            <p style={{ color: '#6b7280', marginTop: '4px' }}>
              {risk.level === 'Low Risk' 
                ? 'Great news! Your eye scans look healthy.'
                : risk.level === 'Moderate Risk'
                ? 'Some findings need monitoring. Let\'s discuss with your doctor.'
                : 'Please schedule an appointment with your eye doctor soon.'}
            </p>
          </div>
        </div>
      </div>

      {/* Findings */}
      <div style={{ 
        backgroundColor: 'white', 
        borderRadius: '12px', 
        padding: '24px',
        marginBottom: '24px',
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      }}>
        <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>What We Found</h3>
        {diseases.length === 0 ? (
          <p style={{ color: '#6b7280' }}>No concerning findings detected. Keep up the great work with your eye health!</p>
        ) : (
          diseases.map((disease, idx) => (
            <div key={idx} style={{ 
              padding: '16px',
              marginBottom: idx < diseases.length - 1 ? '12px' : 0,
              borderRadius: '10px',
              backgroundColor: disease.probability >= 70 ? '#fef2f2' : disease.probability >= 40 ? '#fffbeb' : '#f0fdf4',
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                <span style={{ fontWeight: 600, fontSize: '16px' }}>{disease.name}</span>
                <span style={{
                  padding: '4px 12px',
                  borderRadius: '20px',
                  fontSize: '13px',
                  fontWeight: 600,
                  backgroundColor: 'white',
                  color: disease.probability >= 70 ? '#ef4444' : disease.probability >= 40 ? '#f59e0b' : '#22c55e',
                }}>
                  {disease.probability >= 70 ? '⚠️ Needs Attention' : disease.probability >= 40 ? '👀 Monitor' : '✓ Looking Good'}
                </span>
              </div>
              <p style={{ fontSize: '14px', color: '#6b7280', lineHeight: 1.6 }}>
                {disease.description}
              </p>
            </div>
          ))
        )}
      </div>

      {/* Next Steps */}
      <div style={{ 
        backgroundColor: '#ecfeff', 
        borderRadius: '12px', 
        padding: '24px',
        border: '1px solid #0891b220',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
          <Lightbulb size={20} style={{ color: '#0891b2' }} />
          <h3 style={{ fontSize: '18px', fontWeight: 600, color: '#0891b2' }}>What You Should Do Next</h3>
        </div>
        <ul style={{ margin: 0, paddingLeft: '20px', color: '#374151', lineHeight: 1.8 }}>
          {risk.level === 'High Risk' && (
            <>
              <li>Schedule an appointment with your eye specialist as soon as possible</li>
              <li>Bring this report to your appointment</li>
              <li>Don't delay - early treatment is important</li>
            </>
          )}
          {risk.level === 'Moderate Risk' && (
            <>
              <li>Schedule a follow-up appointment within the next 3-6 months</li>
              <li>Keep track of any changes in your vision</li>
              <li>Share this report with your eye doctor</li>
            </>
          )}
          {risk.level === 'Low Risk' && (
            <>
              <li>Continue with regular annual eye check-ups</li>
              <li>Maintain a healthy lifestyle for good eye health</li>
              <li>Protect your eyes from UV light with sunglasses</li>
            </>
          )}
        </ul>
      </div>
    </div>
  );
}